### PR TITLE
Amdify javascript

### PR DESCRIPTION
**Pull request by djowett-ftw**
Also pulls the Plone 5 toolbar back to the left edge of the screen.

### CODE REVIEW

**Comment by djowett-ftw** [comment]
@maethu this will help you for OGB-59

**Review by maethu — APPROVED** [review]
@djowett-ftw But please remove the yarn lock file (gitignore)

**Review by maethu — CHANGES_REQUESTED** [review]
Add changelog entry

**Comment by djowett-ftw** [comment]
> Add changelog entry

Ok, done!

**Pull request merged**
